// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"time"
)

type Task struct {
	ID        int32     `db:"id"`
	UserID    int32     `db:"user_id"`
	Title     string    `db:"title"`
	Done      bool      `db:"done"`
	CreatedAt time.Time `db:"created_at"`
}

type User struct {
	ID          int32     `db:"id"`
	Role        string    `db:"role"`
	Email       string    `db:"email"`
	PasswdHash  []byte    `db:"passwd_hash"`
	DisplayName string    `db:"display_name"`
	CreatedAt   time.Time `db:"created_at"`
}
