// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package repository

import (
	"time"
)

type Task struct {
	ID        int32
	UserID    int32
	Title     string
	Done      bool
	CreatedAt time.Time
}

type User struct {
	ID          int32
	Role        string
	Email       string
	PasswdHash  []byte
	DisplayName string
	CreatedAt   time.Time
}
