// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: query.sql

package repository

import (
	"context"
)

const getUserByEmail = `-- name: GetUserByEmail :one
select id, role, email, passwd_hash, display_name, created_at from users where email = $1 limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Email,
		&i.PasswdHash,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}
