# available config options: https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/configuration.go
package: domain
output: schema.gen.go
generate:
  models: true
compatibility:
  always-prefix-enum-values: true
additional-imports: []
output-options:
  skip-prune: true
  user-templates:
    request-bodies.tmpl: "// request-bodies.tmpl (empty)"

    param-types.tmpl: |
      {{range .}}{{$opid := .OperationId}}
      {{range .TypeDefinitions}}
      // {{.TypeName}} defines parameters for {{$opid}}.
      type {{.TypeName}} {{if .IsAlias}}={{end}} {{.Schema.TypeDecl}}
      {{end}}
      {{end}}

    typedef.tmpl: |
      {{range .Types}}{{$typeNameHead := slice .TypeName 0 4}}
      {{if ne $typeNameHead "Resp"}}
      {{if .Schema.Description}}{{toGoComment .Schema.Description .TypeName}}{{else}}// {{.TypeName}} defines model for {{.JsonName}}.{{end}}
      type {{.TypeName}} {{.Schema.TypeDecl}}
      {{end}}
      {{end}}
