# available config options: https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/configuration.go
package: domain
output: schema.gen.go
generate:
  models: true
compatibility:
  always-prefix-enum-values: true
additional-imports: []
output-options:
  skip-prune: true
