// Package domain provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package domain

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	AccessTokenScopes = "accessToken.Scopes"
)

// Defines values for TaskStatusFilter.
const (
	TaskStatusFilterAny  TaskStatusFilter = "any"
	TaskStatusFilterDone TaskStatusFilter = "done"
	TaskStatusFilterTodo TaskStatusFilter = "todo"
)

// AuthToken defines model for AuthToken.
type AuthToken struct {
	AccessToken string `json:"accessToken"`
}

// Password defines model for Password.
type Password string

// ReqCreateAuthToken defines model for ReqCreateAuthToken.
type ReqCreateAuthToken struct {
	Email    openapi_types.Email `json:"email"`
	Password Password            `json:"password"`
}

// ReqCreateTask defines model for ReqCreateTask.
type ReqCreateTask struct {
	Title TaskTitle `json:"title"`
}

// ReqCreateUser defines model for ReqCreateUser.
type ReqCreateUser struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Password    Password            `json:"password"`
}

// ReqPatchTask defines model for ReqPatchTask.
type ReqPatchTask struct {
	Done  *bool      `json:"done,omitempty"`
	Title *TaskTitle `json:"title,omitempty"`
}

// Task defines model for Task.
type Task struct {
	CreatedAt time.Time `json:"createdAt"`
	Done      bool      `json:"done"`
	Id        TaskID    `json:"id"`
	Title     string    `json:"title"`
}

// TaskID defines model for TaskID.
type TaskID uint64

// TaskList defines model for TaskList.
type TaskList struct {
	Items      []Task `json:"items"`
	TotalCount int    `json:"totalCount"`
}

// TaskStatusFilter タスクの完了状態のフィルタリング指定
type TaskStatusFilter string

// TaskTitle defines model for TaskTitle.
type TaskTitle string

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"createdAt"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          UserID              `json:"id"`
}

// UserID defines model for UserID.
type UserID uint64

// UserList defines model for UserList.
type UserList struct {
	Items      []User `json:"items"`
	TotalCount int    `json:"totalCount"`
}

// ListTasksParams defines parameters for ListTasks.
type ListTasksParams struct {
	// Status タスクの完了状態のフィルタリング指定
	Status *TaskStatusFilter `form:"status,omitempty" json:"status,omitempty"`
}

// request-bodies.tmpl (empty)
