# available config options: https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/configuration.go
package: rest
output: schema.gen.go
generate:
  models: true
compatibility:
  always-prefix-enum-values: true
additional-imports: []
output-options:
  skip-prune: true
  user-templates:
    # see: https://github.com/deepmap/oapi-codegen/tree/master/pkg/codegen/templates
    request-bodies.tmpl: "// request-bodies.tmpl (empty)"
