# available config options: https://github.com/deepmap/oapi-codegen/blob/master/pkg/codegen/configuration.go
package: rest
output: interface.gen.go
generate:
  echo-server: true
compatibility:
  always-prefix-enum-values: true
additional-imports:
  - package: "github.com/arumakan1727/todo-app-go-react/domain"
    alias: "."
output-options:
  skip-prune: true
  user-templates:
    # see: https://github.com/deepmap/oapi-codegen/tree/master/pkg/codegen/templates
    echo/echo-register.tmpl: "// echo-register.tmpl (empty)"
